# image: ruby:2.6.3
image: ruby:3.3.7

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - "gem install bundler:2.0.1 && bundle install"

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
